let state={mode:'projects',projects:[],presets:[],projectRoot:null,presetRoot:null,library:{clients:[],items:{}}};
let activeFilter={type:'all',value:null},editingItem=null,selectionMode=false;
const selected=new Set(),fontCache={},$=(id)=>document.getElementById(id);
const items=()=>state.mode==='projects'?state.projects:state.presets;
const root=()=>state.mode==='projects'?state.projectRoot:state.presetRoot;
const metadata=(item)=>state.library.items[item.id]||{};
const client=(id)=>state.library.clients.find((c)=>c.id===id);
function toast(message,error=false){const el=$('toast');el.textContent=message;el.style.background=error?'#ffd9dd':'#effcf9';el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
function bytes(value){if(!value)return 'Calculando tamanho…';const units=['B','KB','MB','GB'];let n=value,u=0;while(n>=1024&&u<3){n/=1024;u++}return `${n.toFixed(u?1:0)} ${units[u]}`}
function loading(show,title='Processando…',detail='Preparando operação.'){if(show){$('loading-title').textContent=title;$('loading-detail').textContent=detail;$('loading-percent').textContent='0%';$('progress-fill').style.width='0%';$('progress-size').textContent='Calculando tamanho…';$('progress-eta').textContent='Estimando tempo…'}$('loading').classList.toggle('show',show);$('loading').setAttribute('aria-hidden',String(!show));document.body.classList.toggle('app-busy',show)}
window.capcut.onProgress((data)=>{const percent=Math.max(0,Math.min(100,data.percent||0));$('loading-percent').textContent=`${percent}%`;$('progress-fill').style.width=`${percent}%`;$('loading-detail').textContent=data.phase||'Processando';$('progress-size').textContent=data.total?`${bytes(data.processed)} de ${bytes(data.total)}`:'Analisando arquivos…';$('progress-eta').textContent=data.remaining===null||data.remaining===undefined?'Estimando tempo…':data.remaining<2?'Finalizando…':`Cerca de ${data.remaining}s restantes`});
function result(title,message,filePath){$('modal-title').textContent=title;$('modal-message').textContent=message;$('modal-path').textContent=filePath;$('result-modal').classList.add('show')}
function closeResult(){$('result-modal').classList.remove('show')}
function date(ms){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(ms))}
function filteredItems(){const now=Date.now();return items().filter((item)=>{const m=metadata(item);if(activeFilter.type==='favorites')return m.favorite;if(activeFilter.type==='recent')return now-item.modified<7*86400000;if(activeFilter.type==='unassigned')return !m.clientId;if(activeFilter.type==='client')return m.clientId===activeFilter.value;if(activeFilter.type==='folder'){const [clientId,...folder]=activeFilter.value.split('|');return m.clientId===clientId&&m.folder===folder.join('|')}return true})}
function selectFilter(type,value=null){activeFilter={type,value};document.querySelectorAll('.filter,.client-filter,.folder-filter').forEach((el)=>el.classList.toggle('active',el.dataset.type===type&&String(el.dataset.value||'')===String(value||'')));render()}
function button(label,className,handler){const el=document.createElement('button');el.textContent=label;el.className=className||'';el.onclick=handler;return el}
function renderSidebar(){const list=$('client-list');list.innerHTML='';for(const c of state.library.clients){const group=document.createElement('div');group.className='client-group';const clientRow=document.createElement('div');clientRow.className='library-row';const main=button(c.name,'client-filter',()=>selectFilter('client',c.id));main.dataset.type='client';main.dataset.value=c.id;const dot=document.createElement('span');dot.className='client-dot';dot.style.background=c.color;main.prepend(dot);const removeClient=button('×','library-delete',async(event)=>{event.stopPropagation();if(!confirm(`Excluir o cliente “${c.name}” da organização?\n\nNenhum arquivo do CapCut será apagado.`))return;state.library=await window.capcut.libraryDeleteClient(c.id);if(activeFilter.type==='client'&&activeFilter.value===c.id)activeFilter={type:'all',value:null};render();toast('Cliente excluído da organização.')});removeClient.title='Excluir cliente';clientRow.append(main,removeClient);group.append(clientRow);const folders=[...new Set(items().filter((i)=>metadata(i).clientId===c.id).map((i)=>metadata(i).folder).filter(Boolean))].sort();for(const folder of folders){const row=document.createElement('div');row.className='library-row folder-row';const child=button(folder,'folder-filter',()=>selectFilter('folder',`${c.id}|${folder}`));child.dataset.type='folder';child.dataset.value=`${c.id}|${folder}`;const removeFolder=button('×','library-delete',async(event)=>{event.stopPropagation();if(!confirm(`Excluir a pasta virtual “${folder}”?\n\nOs itens continuarão no cliente ${c.name}.`))return;state.library=await window.capcut.libraryDeleteFolder(c.id,folder);if(activeFilter.type==='folder'&&activeFilter.value===`${c.id}|${folder}`)activeFilter={type:'client',value:c.id};render();toast('Pasta removida da organização.')});removeFolder.title='Excluir pasta';row.append(child,removeFolder);group.append(row)}list.append(group)}}
function updateBulk(){const count=selected.size;$('selected-count').textContent=count;$('bulk-bar').hidden=!selectionMode;$('select-all').textContent=selectionMode?'Selecionar todos':'Selecionar';$('bulk-apply').disabled=!count}
function render(){renderSidebar();const query=$('search').value.toLowerCase();const shown=filteredItems().filter((item)=>(metadata(item).alias||item.name).toLowerCase().includes(query)||item.name.toLowerCase().includes(query));$('count').textContent=shown.length;$('empty').style.display=shown.length?'none':'block';$('empty').querySelector('h3').textContent=state.mode==='presets'?'Nenhuma predefinição encontrada':'Nenhum projeto encontrado';$('projects').innerHTML='';for(const item of shown){const m=metadata(item),c=client(m.clientId),card=document.createElement('article');card.className=`card${selected.has(item.id)?' selected':''}`;if(selectionMode){const check=document.createElement('input');check.type='checkbox';check.className='card-select';check.checked=selected.has(item.id);check.setAttribute('aria-label',`Selecionar ${item.name}`);check.onchange=()=>{check.checked?selected.add(item.id):selected.delete(item.id);render()};card.append(check)}const thumb=document.createElement('div');thumb.className='thumbnail';if(item.thumbnail){const img=document.createElement('img');img.src=item.thumbnail;img.alt='';thumb.append(img)}else thumb.textContent=state.mode==='presets'?'P':'▶';const title=document.createElement('h3');title.textContent=m.alias||item.name;title.title=item.name;const meta=document.createElement('small');meta.textContent=`${item.kind==='file'?'Arquivo · ':''}Modificado em ${date(item.modified)}`;const tools=document.createElement('div');tools.className='card-tools';const badges=document.createElement('div');badges.className='badges';if(c){const badge=document.createElement('span');badge.className='badge';badge.textContent=c.name;badges.append(badge)}if(m.folder){const badge=document.createElement('span');badge.className='badge';badge.textContent=m.folder;badges.append(badge)}for(const tag of m.tags||[]){const badge=document.createElement('span');badge.className='badge';badge.textContent=`#${tag}`;badges.append(badge)}if(m.favorite){const badge=document.createElement('span');badge.className='badge favorite-star';badge.textContent='★';badges.append(badge)}if(fontCache[item.id]){const missing=fontCache[item.id].filter((f)=>!f.installed).length;const badge=document.createElement('span');badge.className=`badge ${missing?'font-missing':'font-ok'}`;badge.textContent=missing?`${missing} fonte(s) ausente(s)`:'Fontes OK';badges.append(badge)}tools.append(badges,button('Organizar','organize-btn',()=>openOrganizer(item)));const actions=document.createElement('div');actions.className='actions';for(const format of ['zip','7z'])actions.append(button(`Exportar ${format.toUpperCase()}`,'',function(){exportOne(item.name,format,this)}));card.append(thumb,title,meta,tools,actions);$('projects').append(card)}updateBulk()}
function clientOptions(select,selectedValue=''){select.innerHTML='';const none=document.createElement('option');none.value='';none.textContent='Sem cliente';select.append(none);for(const c of state.library.clients){const option=document.createElement('option');option.value=c.id;option.textContent=c.name;select.append(option)}select.value=selectedValue}
function applyMode(){const preset=state.mode==='presets';activeFilter={type:'all',value:null};selected.clear();selectionMode=false;document.querySelectorAll('.tab').forEach((t)=>t.classList.toggle('active',t.dataset.mode===state.mode));$('subtitle').textContent=preset?'Importe, organize e exporte as predefinições do CapCut.':'Importe, organize e exporte projetos completos com segurança.';$('import').textContent=preset?'＋ Importar predefinições':'＋ Importar projeto';$('root-label').textContent=preset?'PASTA DE PREDEFINIÇÕES':'PASTA DE PROJETOS';$('section-title').textContent=preset?'Predefinições':'Projetos';$('search').placeholder=preset?'Buscar predefinição…':'Buscar projeto…';$('root').textContent=root()||'Não encontrada';$('root').title=root()||'';document.querySelector('.filter[data-filter="all"]').classList.add('active');render()}
async function load(feedback=false){const btn=$('refresh');if(feedback){btn.disabled=true;btn.classList.add('rotating')}try{const [s,library]=await Promise.all([window.capcut.status(),window.capcut.libraryGet()]);Object.assign(state,s);state.library=library;$('capcut').textContent=s.capcut?'Instalado':'Não localizado';applyMode();if(feedback)toast(`${items().length} itens atualizados.`)}catch(e){toast(e.message,true)}finally{btn.disabled=false;btn.classList.remove('rotating')}}
async function openOrganizer(item){editingItem=item;const m=metadata(item);$('organize-title').textContent=m.alias||item.name;$('item-real-name').value=item.name;$('rename-label').hidden=state.mode!=='projects';$('item-alias').value=m.alias||'';$('item-folder').value=m.folder||'';$('item-tags').value=(m.tags||[]).join(', ');$('item-favorite').checked=Boolean(m.favorite);clientOptions($('item-client'),m.clientId||'');$('item-folder').disabled=!m.clientId;$('font-summary').textContent='Analisando referências do CapCut…';$('font-list').innerHTML='';$('organize-modal').classList.add('show');try{const fonts=fontCache[item.id]||await window.capcut.fontInfo(state.mode,item.id);fontCache[item.id]=fonts;const missing=fonts.filter((f)=>!f.installed).length;$('font-summary').textContent=!fonts.length?'Nenhuma referência de fonte encontrada.':`${fonts.length} detectada(s), ${missing} ausente(s).`;$('font-list').innerHTML='';for(const font of fonts){const pill=document.createElement('span');pill.className=`font-pill ${font.installed?'font-ok':'font-missing'}`;pill.textContent=`${font.installed?'✓':'!'} ${font.name}`;$('font-list').append(pill)}render()}catch{$('font-summary').textContent='Não foi possível analisar as fontes.'}}
async function exportOne(name,format,btn){btn.disabled=true;const preset=state.mode==='presets';try{const pending=preset?window.capcut.exportPreset(name,format):window.capcut.exportProject(name,format);loading(true,`Exportando “${name}”…`,`Preparando pacote ${format.toUpperCase()}.`);const r=await pending;if(!r.canceled)result(preset?'Predefinição exportada com sucesso':'Projeto exportado com sucesso',`Pacote pronto.${r.fonts?` Inclui ${r.fonts} fonte(s).`:''}`,r.filePath)}catch(e){toast(`Não foi possível exportar: ${e.message}`,true)}finally{loading(false);btn.disabled=false}}
document.querySelectorAll('.tab').forEach((tab)=>tab.onclick=()=>{state.mode=tab.dataset.mode;$('search').value='';applyMode()});document.querySelectorAll('.filter').forEach((b)=>{b.dataset.type=b.dataset.filter;b.dataset.value='';b.onclick=()=>selectFilter(b.dataset.filter)});
$('add-client').onclick=async()=>{const name=$('client-name').value.trim();if(!name)return;try{state.library=await window.capcut.libraryAddClient({name,color:$('client-color').value});$('client-name').value='';render()}catch(e){toast(e.message,true)}};
$('item-client').onchange=()=>{$('item-folder').disabled=!$('item-client').value;if(!$('item-client').value)$('item-folder').value=''};
$('organize-save').onclick=async()=>{if(!editingItem)return;try{let targetId=editingItem.id;if(state.mode==='projects'&&$('item-real-name').value.trim()!==editingItem.name){const renamed=await window.capcut.renameProject(editingItem.id,$('item-real-name').value);state.projects=renamed.projects;state.library=renamed.library;targetId=renamed.newId||targetId}state.library=await window.capcut.libraryUpdateItem(targetId,{alias:$('item-alias').value,clientId:$('item-client').value,folder:$('item-client').value?$('item-folder').value:'',tags:$('item-tags').value.split(','),favorite:$('item-favorite').checked});$('organize-modal').classList.remove('show');render();toast('Organização salva.')}catch(e){toast(e.message,true)}};
$('select-all').onclick=()=>{if(!selectionMode){selectionMode=true}else{for(const item of filteredItems())selected.add(item.id)}clientOptions($('bulk-client'));render()};$('bulk-cancel').onclick=()=>{selectionMode=false;selected.clear();render()};$('bulk-client').onchange=()=>{$('bulk-folder').disabled=!$('bulk-client').value;if(!$('bulk-client').value)$('bulk-folder').value=''};$('bulk-apply').onclick=async()=>{try{state.library=await window.capcut.libraryUpdateItems([...selected],{clientId:$('bulk-client').value,folder:$('bulk-client').value?$('bulk-folder').value:'',tags:$('bulk-tags').value.split(',')});const count=selected.size;selected.clear();selectionMode=false;render();toast(`${count} item(ns) organizados.`)}catch(e){toast(e.message,true)}};
$('organize-close').onclick=$('organize-cancel').onclick=()=>$('organize-modal').classList.remove('show');$('choose').onclick=async()=>{try{const preset=state.mode==='presets',r=preset?await window.capcut.choosePresetRoot():await window.capcut.chooseRoot();if(preset){state.presetRoot=r.presetRoot;state.presets=r.presets}else{state.projectRoot=r.projectRoot;state.projects=r.projects}applyMode()}catch(e){toast(e.message,true)}};$('open').onclick=()=>state.mode==='presets'?window.capcut.openPresetRoot():window.capcut.openRoot();$('refresh').onclick=()=>load(true);
$('restart-capcut').onclick=async()=>{try{const r=await window.capcut.restartCapCut();if(!r.canceled)toast('CapCut reiniciado. Os projetos foram recarregados.')}catch(e){toast(e.message,true)}};
$('import').onclick=async()=>{const b=$('import'),preset=state.mode==='presets';b.disabled=true;try{const pending=preset?window.capcut.importPreset():window.capcut.importProject();loading(true,preset?'Importando predefinições…':'Importando projeto…','Validando pacote.');const r=await pending;if(!r.canceled){const ft=r.fontResult?.found?` ${r.fontResult.installed} de ${r.fontResult.found} fonte(s) instalada(s).`:'';if(preset){state.presets=r.presets;result('Predefinições importadas',`${r.installed.length} item(ns) instalado(s).${ft}`,r.destination)}else{state.projects=r.projects;result('Projeto importado',`“${r.name}” já está disponível.${ft}`,r.destination)}render()}}catch(e){toast(`Não foi possível importar: ${e.message}`,true)}finally{loading(false);b.disabled=false}};
$('modal-close').onclick=$('modal-done').onclick=closeResult;$('modal-reveal').onclick=async()=>{try{await window.capcut.revealLast()}catch(e){toast(e.message,true)}};$('search').oninput=render;load();
